apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvolucaclbisma
  name: msvolucaclbisma
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msvolucaclbisma
  template:
    metadata:
      labels:
        app: msvolucaclbisma
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:msvolumecalculatebiggerandsmalleryear-v100
          name: msvolucaclbisma
          ports:
          - containerPort: 3050
            name: msvolucaclbisma
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  