apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvolcalcitens
  name: msvolcalcitens
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msvolcalcitens
  template:
    metadata:
      labels:
        app: msvolcalcitens
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:msvolumecalculateitens-v1010
          name: msvolcalcitens
          ports:
          - containerPort: 3040
            name: msvolcalcitens
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
                  
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  