apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvolucaclbisma
  name: msvolucaclbisma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msvolucaclbisma
  template:
    metadata:
      labels:
        app: msvolucaclbisma
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:msvolumecalculatebiggerandsmalleryear-v3000
          name: msvolucaclbisma
          ports:
          - containerPort: 3050
            name: msvolucaclbisma
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            