apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msretenvol
  name: msretenvol
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msretenvol
  template:
    metadata:
      labels:
        app: msretenvol
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:msretentionvolume-v110
          name: msretenvol
          ports:
          - containerPort: 3030
            name: msretenvol
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  