apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvolcalcitens
  name: msvolcalcitens
spec:
  replicas: 10
  selector:
    matchLabels:
      app: msvolcalcitens
  template:
    metadata:
      labels:
        app: msvolcalcitens
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:msvolumecalculateitens-v3000
          name: msvolcalcitens
          ports:
          - containerPort: 3040
            name: msvolcalcitens
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                