apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cron-reports
  name: cron-reports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-reports
  template:
    metadata:
      labels:
        app: cron-reports
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:

        - image: archiocloud/develop:archio-cron-v10
          name: cron-reports
          envFrom:
            - secretRef:
                name: api-secret
          resources:
            limits:
              memory: 300Mi
              cpu: 500m    
          