apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-arc-c-arc
  name: archio-arc-c-arc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: archio-arc-c-arc
  template:
    metadata:
      labels:
        app: archio-arc-c-arc
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-archive-create-archive-v4000
        name: archio-arc-c-arc
        ports:
        - containerPort: 1013
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_HOST
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_HOST                
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                      
            - name: PRINT_ERROR_ARCHIVES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: PRINT_ERROR_ARCHIVES                            