apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mslcalccompany
  name: mslcalccompany
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mslcalccompany
  template:
    metadata:
      labels:
        app: mslcalccompany
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:ms-calculete_everything-v11 ####
          name: mslcalccompany
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  