apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archio-ocr
  name: archio-ocr
spec:
  replicas: 4
  selector:
    matchLabels:
      app: archio-ocr
  template:
    metadata:
      labels:
        app: archio-ocr
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:archio-ocr-v3000
          name: archio-ocr
          ports:
          - containerPort: 7001
            name: archio-ocr
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            