apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archio-ocr
  name: archio-ocr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-ocr
  template:
    metadata:
      labels:
        app: archio-ocr
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:archio-ocrlocal-v33
          name: archio-ocr
          ports:
          - containerPort: 7001
            name: archio-ocr
          # env:
          #   - name: AMPQ_QUEUE
          #     valueFrom:
          #        secretKeyRef: 
          #         name: api-sec-ampq-queue
          #         key: AMPQ_QUEUE
          #   - name: CLOUD_QUEUE
          #     valueFrom:
          #        secretKeyRef: 
          #         name: api-sec-cloud-queue
          #         key: CLOUD_QUEUE      
          #   - name: KULSTER_QUEUES
          #     valueFrom:
          #        secretKeyRef: 
          #         name: api-sec-kluster-queue
          #         key: KULSTER_QUEUES            
          #   - name: MONGO_ACESS
          #     valueFrom:
          #        secretKeyRef: 
          #         name: api-sec-mongo-access
          #         key: MONGO_ACESS                  