apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-sponsor
  name: admin-sponsor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-sponsor
  template:
    metadata:
      labels:
        app: admin-sponsor
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:admin-sponsorv2
          name: admin-sponsor
          env:
            - name: AMPQ_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-admin-all
                  key: AMPQ_URL
            - name: MONGO_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-admin-all
                  key: MONGO_URL      
            - name: JWT_SECRET
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-admin-all
                  key: JWT_SECRET    
            - name: EXPIRES_IN
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-admin-all
                  key: EXPIRES_IN          
            - name: APP_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-admin-all
                  key: APP_URL          


