apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: profiles
  name: profiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:profilesv4
          name: profiles
          env:
            - name: AMPQ_URL
              valueFrom:
                secretKeyRef:
                  name: api-sec-admin-all
                  key: AMPQ_URL
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: api-sec-admin-all
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-sec-admin-all
                  key: JWT_SECRET
            - name: EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: api-sec-admin-all
                  key: EXPIRES_IN
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: api-sec-admin-all
                  key: APP_URL

