apiVersion: v1
kind: Service
metadata:
  labels:
    app: emailservice
  name: emailservice
  namespace: backendarchio
spec:
  type: LoadBalancer
  ports:
  - name: emailservice
    port: 5000  
    targetPort: 5000    
  selector:
    app: emailservice