apiVersion: v1
kind: Secret
metadata:
  name: api-sec-archio-all
type: Opaque


data:
  RABBITMQ_CONNECTION_URL: YW1xcHM6Ly94ZGNqaGplbTpLXzcxY2dNZ0VHWmgtWXIweXFXUWc4c1VBSUZSQWVvaEBrZWJuZWthaXNlLmxtcS5jbG91ZGFtcXAuY29tL3hkY2poamVt
  MONGO_ACESS: bW9uZ29kYjovL2RldmVsb3BhcmNoaW86NzFnR3lhNzR6V0hMRU44NUBjbHVzdGVyMC1zaGFyZC0wMC0wMC1ycjZzeC5tb25nb2RiLm5ldDoyNzAxNy9lYXJjaGl2ZT9zc2w9dHJ1ZSZyZXBsaWNhU2V0PUNsdXN0ZXIwLXNoYXJkLTAmYXV0aFNvdXJjZT1hZG1pbg==
  REDIS_HOST: cmVkaXM= 
  REDIS_PORT: NjM3OQ==
  TEMP: Li9URU1QLw==
  OUTPUT: Li9PVVRQVVQv
  ASSETS: Li9hc3NldHM=
  PRINT_ERROR_ARCHIVES: aHR0cHM6Ly9hcmNoaW9tYWludGVzdGVzLmFyY2hpby5jb20uYnI=
  RABBITMQ_IMPORT_CONNECTION_URL: YW1xcHM6Ly94ZGNqaGplbTpLXzcxY2dNZ0VHWmgtWXIweXFXUWc4c1VBSUZSQWVvaEBrZWJuZWthaXNlLmxtcS5jbG91ZGFtcXAuY29tL3hkY2poamVt
  


