apiVersion: v1
kind: Secret
metadata:
  name: api-sec-archio-all
type: Opaque
data:
  RABBITMQ_CONNECTION_URL: YW1xcHM6Ly94ZGNqaGplbTpLXzcxY2dNZ0VHWmgtWXIweXFXUWc4c1VBSUZSQWVvaEBrZWJuZWthaXNlLmxtcS5jbG91ZGFtcXAuY29tL3hkY2poamVt
  MONGO_ACESS: bW9uZ29kYjovL2VhcmNoaXZlVGVzdGVyOmNkaDB0QVlVRkpYRE1CM3RAY2x1c3RlcjAtc2hhcmQtMDAtMDAtcnI2c3gubW9uZ29kYi5uZXQ6MjcwMTcvZWFyY2hpdmU/c3NsPXRydWUmcmVwbGljYVNldD1DbHVzdGVyMC1zaGFyZC0wJmF1dGhTb3VyY2U9YWRtaW4=
  REDIS_HOST: cmVkaXM= 
  REDIS_PORT: NjM3OQ==
  TEMP: Li9URU1QLw==
  OUTPUT: Li9PVVRQVVQv
  PRINT_ERROR_ARCHIVES: aHR0cHM6Ly9hcmNoaW9tYWludGVzdGVzLmFyY2hpby5jb20uYnI=


  


  


