apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Tamanho do armazenamento persistente
  storageClassName: standard # Classe de armazenamento
