apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-images
  name: archio-images
spec:
  type: ClusterIP
  ports:
  - name: "archio-images-service"
    port: 80
    targetPort: 3004    
  selector:
    app: archio-images