apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-red-departament
  name: archio-red-departament
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archio-red-departament
  template:
    metadata:
      labels:
        app: archio-red-departament
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-archive-reduce-departament-v05 fazer amanhá
      - image: archiocloud/develop:archio-archive-reduce-departament-v06
        name: archio-red-departament
        ports:
        - containerPort: 3032
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                
            - name: REDIS_HOST
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_HOST    


                  # ok                  