apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-red-document
  name: archio-red-document
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archio-red-document
  template:
    metadata:
      labels:
        app: archio-red-document
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-archive-reduce-document-v09 para fazer amanhá
      - image: archiocloud/develop:archio-archive-reduce-document-v10
        name: archio-red-document
        ports:
        - containerPort: 3033
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                
                               


                              #  ok