apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-import-volume
  name: archio-import-volume
  namespace: backendarchio
spec:
  type: LoadBalancer
  ports:
  - name: "archio-import-volume-service"
    port: 3002
    targetPort: 3002   
  selector:
    app: archio-import-volume