apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-ocre
  name: archio-ocre
spec:
  type: ClusterIP
  ports:
  - name: "archio-ocre"
    port: 7002
    targetPort: 7002 
  selector:
    app: archio-ocre