apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-split
  name: archio-split
spec:
  type: ClusterIP
  ports:
  - name: "archio-split"
    port: 6000
    targetPort: 6000   
  selector:
    app: archio-split