apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-app
  name: archio-app  
spec:
  type: ClusterIP
  ports:
  - name: "archio-app-service"
    port: 80
    targetPort: 80    
  selector:
    app: archio-app