apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-arc-r-xlsx
  name: archio-arc-r-xlsx
spec:
  type: ClusterIP
  ports:
  - name: "archio-arc-r-xlsx"
    port: 1011
    targetPort: 1011   
  selector:
    app: archio-arc-r-xlsx