apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-main
  name: archio-main
  namespace: backendarchio
spec:
  type: LoadBalancer
  ports:
  - name: "archio-main-service"
    port: 80
    targetPort: 80    
  selector:
    app: archio-main