apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-upload
  name: archio-upload
spec:
  type: ClusterIP
  ports:
  - name: "archio-upload-service"
    port: 80
    targetPort: 2010    
  selector:
    app: archio-upload