apiVersion: v1
kind: Service
metadata:
  labels:
    app: export-archio
  name: export-archio
  namespace: backendarchio
spec:
  type: LoadBalancer
  ports:
  - name: "export-archio-service"
    port: 3003
    targetPort: 3003    
  selector:
    app: export-archio