apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-try
  name: archio-try
spec:
  type: ClusterIP
  ports:
  - name: "archio-try-service"
    port: 80
    targetPort: 3020    
  selector:
    app: archio-try