apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-arc-c-arc
  name: archio-arc-c-arc
spec:
  type: ClusterIP
  ports:
  - name: "archio-arc-c-arc"
    port: 1013
    targetPort: 1013  
  selector:
    app: archio-arc-c-arc