apiVersion: v1
kind: Service
metadata:
  labels:
    app: export-archio
  name: export-archio  
spec:
  type: ClusterIP
  ports:
  - name: "export-archio-service"
    port: 80
    targetPort: 3003    
  selector:
    app: export-archio