apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-arc-c-vol
  name: archio-arc-c-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archio-arc-c-vol
  template:
    metadata:
      labels:
        app: archio-arc-c-vol
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-archive-create-volume-v4011
        name: archio-arc-c-vol
        ports:
        - containerPort: 1012
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_HOST
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_HOST                
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT     


                  # ok                 