apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-arc-c-vol
  name: archio-arc-c-vol
spec:
  type: ClusterIP
  ports:
  - name: "archio-arc-c-vol"
    port: 1012
    targetPort: 1012  
  selector:
    app: archio-arc-c-vol