apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-main
  name: backend-main  
spec:
  type: ClusterIP
  ports:
  - name: "backend-main-service"
    port: 3000
    targetPort: 3000    
  selector:
    app: archio-main
