apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-delete-files
  name: ms-delete-files
spec:
  type: ClusterIP
  ports:
  - name: "ms-delete-files"
    port: 3029
    targetPort: 3029
  selector:
    app: ms-delete-files