apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-export-demand-vol
  name: ms-export-demand-vol  
spec:
  type: ClusterIP
  ports:
  - name: "ms-export-demand-vol-service"
    port: 3078
    targetPort: 3078 
  selector:
    app: ms-export-demand-vol