apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-export-demand-archive
  name: ms-export-demand-archive
spec:
  type: ClusterIP
  ports:
  - name: "ms-export-demand-archice-service"
    port: 3079
    targetPort: 3079
  selector:
    app: ms-export-demand-archive