apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-general-volumes
  name: ms-general-volumes
spec:
  type: ClusterIP
  ports:
  - name: "ms-general-volumes"
    port: 3050
    targetPort: 3050
  selector:
    app: ms-general-volumes