apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-restruct-archives
  name: ms-restruct-archives
spec:
  type: ClusterIP
  ports:
  - name: "ms-restruct-archives"
    port: 3034
    targetPort: 3034   
  selector:
    app: ms-restruct-archives