apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-read-worksheet
  name: ms-read-worksheet
spec:
  type: ClusterIP
  ports:
  - name: "ms-read-worksheet"
    port: 80
    targetPort: 3042   
  selector:
    app: ms-read-worksheet