apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-workseet-save
  name: ms-workseet-save
spec:
  type: ClusterIP
  ports:
  - name: "ms-workseet-save"
    port: 80
    targetPort: 3043
  selector:
    app: ms-workseet-save