apiVersion: v1
kind: Service
metadata:
  labels:
    app: stream-data-archive
  name: stream-data-archive
spec:
  type: ClusterIP
  ports:
  - name: "stream-data-archive-service"
    port: 3010
    targetPort: 3010
  selector:
    app: stream-data-archive