apiVersion: v1
kind: Service
metadata:
  labels:
    app: stream-data-volumes
  name: stream-data-volumes
spec:
  type: ClusterIP
  ports:
  - name: "stream-data-volumese-service"
    port: 3007
    targetPort: 3007
  selector:
    app: stream-data-volumes