apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: backendarchio
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis