apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
  namespace: backendarchio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage