apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-volume  
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          volumeMounts:
            - mountPath: "/var/lib/rabbitmq"
              name: rabbitmq
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-volume