apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: archio-cron-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cron-archio
  targetCPUUtilizationPercentage: 60  
  
    