apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-control-user
  name: ms-control-user
spec:
  type: ClusterIP
  ports:
  - name: "ms-control-user"
    port: 80
    targetPort: 3032    
  selector:
    app: ms-control-user