apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-notify-user
  name: ms-notify-user
spec:
  type: ClusterIP
  ports:
  - name: "ms-notify-user"
    port: 80
    targetPort: 3036  
  selector:
    app: ms-notify-user