apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-report-contract
  name: ms-report-contract
spec:
  type: ClusterIP
  ports:
  - name: "ms-report-contract"
    port: 80
    targetPort: 3030    
  selector:
    app: ms-report-contract