apiVersion: v1
kind: Secret
metadata:
  name: api-sec-rabbitmq-archio
type: Opaque
data:
  RABBITMQ_CONNECTION_URL: YW1xcHM6Ly93c3Ftdmp4YjpqaW5sMkN2eUNZVGViMXlBTmcxT3ZZYU9qOVNEbllHX0B0b3VnaC1zaWx2ZXItZ2liYm9uLnJtcTUuY2xvdWRhbXFwLmNvbS93c3Ftdmp4Yg==

  

  
  

