---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "codeclou/docker-nginx-self-signed-ssl:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 4443

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 443
    targetPort: 4443
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: testconfigs.example.io
spec:
  group: example.io
  version: v1
  versions:
    - name: v1
      storage: true
      served: true
  names:
    kind: TestConfig
    plural: testconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            TestString:
              description: This is a test string
              type: string
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: test-webhook
webhooks:
- name: testconfigs.example.io
  clientConfig:
    service:
      namespace: default
      name: nginx
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - example.io
    apiVersions:
    - v1
    resources:
    - testconfigs
  failurePolicy: Fail
