apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-mupload
  name: archio-mupload
spec:
  type: ClusterIP
  ports:
  - name: "archio-mupload-service"
    port: 80
    targetPort: 2000    
  selector:
    app: archio-mupload