apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mslvolcalcitens
  name: mslvolcalcitens
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mslvolcalcitens
  template:
    metadata:
      labels:
        app: mslvolcalcitens
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:mslvolumecalculateitens-v303
          name: mslvolcalcitens
          ports:
          - containerPort: 3041
            name: mslvolcalcitens
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            