apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archio-main
  template:
    metadata:
      labels:
        app: archio-main
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-main-v4031 já na nova versao de pesquisa de volumes v4040 em testes
      # - image: archiocloud/develop:archio-main-v4041
      # testes exportacao
      - image: archiocloud/develop:archio-main-v4050
        name: archio-main        
        ports:
        - containerPort: 3000
          name: archio-main    
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT    



                  # ok            