apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: export-archio
  name: export-archio  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: export-archio
  template:
    metadata:
      labels:
        app: export-archio
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-exportsearch-v200 #ok
      - image: archiocloud/develop:archio-exportsearch-v203
        name: export-archio
        # resources:
        #   limits:
        #     memory: 300Mi
        #     cpu: 150m
        ports:
        - containerPort: 3003
          name: export-archio 
        envFrom:
            - secretRef:
                name: api-secret  
        