apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-main
  template:
    metadata:
      labels:
        app: archio-main
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-main-v1032
      ##- image: archiocloud/develop:archio-main-v1005 #tentnado arrumar o bug sem front operacional 808
        name: archio-main        
        ports:
        - containerPort: 3000
          name: archio-main    
        env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  