apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-mupload
  name: archio-mupload 
spec:
  replicas: 7
  selector:
    matchLabels:
      app: archio-mupload
  template:
    metadata:
      labels:
        app: archio-mupload
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-multupload-v13 #ok
      - image: archiocloud/develop:archio-multupload-v14 #ok
        name: archio-mupload        
        ports:
        - containerPort: 2000
          name: archio-mupload
        envFrom:
            - secretRef:
                name: api-secret-upload  
       