apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: export-archio
  name: export-archio  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: export-archio
  template:
    metadata:
      labels:
        app: export-archio
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-exportsearch-v203 estável
      # testes importacao
      - image: archiocloud/develop:archio-exportsearch-v1010
        name: export-archio
        # resources:
        #   limits:
        #     memory: 300Mi
        #     cpu: 150m
        ports:
        - containerPort: 3003
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
          