apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-try
  name: archio-try
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archio-try
  template:
    metadata:
      labels:
        app: archio-try
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-tryqueue-v2
        name: archio-try
        ports:
        - containerPort: 3020
          name: archio-try
        envFrom:
            - secretRef:
                name: api-secret
                name: api-secret-amqp
          
  # versao anterior 402          
# This version includes file transfer.
# It also includes creating packages, selling packages, uploading certificates for digital signatures. That is, it is operational until it is sent to the ocr or subscription queue.