apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  replicas: 5
  selector:
    matchLabels:
      app: archio-main
  template:
    metadata:
      labels:
        app: archio-main
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-main-v310 # versao testes automoatioin docuemntos
      #- image: archiocloud/develop:archio-main-v316 # estavel
      - image: archiocloud/develop:archio-main-v337 # 333 estavelnova pesuisa de volumes v anterior era 320

      
     
        name: archio-main        
        ports:
        - containerPort: 3000
          name: archio-main    
        envFrom:
            - secretRef:
                name: api-secret
          
            
