apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-main
  template:
    metadata:
      labels:
        app: archio-main
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-main-v72 
      # - image: archiocloud/develop:archio-main-v79
      # - image: archiocloud/develop:archio-main-v105 versao estavel
      # - image: archiocloud/develop:archio-main-v121  # versao para teste pesquisa simples 1
      # - image: archiocloud/develop:archio-main-v124  # versao para testes relat'roio estavel em producao
      # - image: archiocloud/develop:archio-main-v201  # versao para testes relat'roio
      # - image: archiocloud/develop:archio-main-v202 estaval
      # - image: archiocloud/develop:archio-main-v205 ultima estavel antes das atualizacoes de importacao
      # - image: archiocloud/develop:archio-main-v216
      - image: archiocloud/develop:archio-main-v220 
      
     
        name: archio-main        
        ports:
        - containerPort: 3000
          name: archio-main    
        envFrom:
            - secretRef:
                name: api-secret
          
            
