apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-imp-vol
  name: archio-imp-vol  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-imp-vol
  template:
    metadata:
      labels:
        app: archio-imp-vol
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-import-volume-v3007
        name: archio-imp-vol
        ports:
        - containerPort: 3002
          name: archio-imp-vol
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                
              

            # ok
            