apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-upload
  name: archio-upload
spec:
  replicas: 10
  selector:
    matchLabels:
      app: archio-upload
  template:
    metadata:
      labels:
        app: archio-upload
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      
      - image:  archiocloud/develop:archio-multupload-v62
      # - image:  archiocloud/develop:archio-upload-v20
      
        name: archio-upload      
        ports:
        - containerPort: 2010
          name: archio-upload
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: environment-archio
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: environment-archio
                  key: MONGO_ACESS      
