apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: backendarchio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: archio
        - name: RABBITMQ_DEFAULT_PASS
          value: archio
        ports:
        - containerPort: 5673        
          name: rabbitmq
        - containerPort: 15673
          name: rabbitmq 
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          emptyDir: {}