apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-imp-vol
  name: archio-imp-vol
  namespace: backendarchio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archio-imp-vol
  template:
    metadata:
      labels:
        app: archio-imp-vol
    spec:
      containers:
      - image: archiocloud/develop-archio-import-volume:v1
        name: archio-imp-vol
        ports:
        - containerPort: 3002
          name: archio-imp-vol
