apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archio-ocre
  name: archio-ocre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-ocre
  template:
    metadata:
      labels:
        app: archio-ocre
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:archio-ocre-v4020
          name: archio-ocre
          ports:
          - containerPort: 7002
            name: archio-ocre
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS
            - name: PROCESS_OCR
              value: EXCLUSIVE-PROCESS-OCR             
            