apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-upload
  name: archio-upload
  namespace: backendarchio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archio-upload
  template:
    metadata:
      labels:
        app: archio-upload
    spec:
      containers:
      - image: wellingtondevops/dev-upload-bucket 
        name: archio-upload
        lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "cp ./credentials.json" , "./credentials.json ."]
        env:
        - name: APP_NAME
          value: uploadBucket
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ./credentials.json
        - name: GCLOUD_PROJECT
          value: archioqa  
        - name: GCS_BUCKET
          value: archiotest
        - name: MONGO_URL
          value: mongodb://earchiveTester:cdh0tAYUFJXDMB3t@cluster0-shard-00-00-rr6sx.mongodb.net:27017/earchive?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
        ports:
        - containerPort: 2000
          name: archio-upload
