apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  replicas: 4
  selector:
    matchLabels:
      app: archio-main
  template:
    metadata:
      labels:
        app: archio-main
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-main-v402
        name: archio-main        
        ports:
        - containerPort: 3000
          name: archio-main    
        envFrom:
            - secretRef:
                name: api-secret
          
            
# This version includes file transfer.
# It also includes creating packages, selling packages, uploading certificates for digital signatures. That is, it is operational until it is sent to the ocr or subscription queue.