apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archio-signature
  name: archio-signature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archio-signature
  template:
    metadata:
      labels:
        app: archio-signature
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:archio-signature-v204
          name: archio-signature
          envFrom:
            - secretRef:
                name: api-secret
          