apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-imp-vol
  name: archio-imp-vol  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-imp-vol
  template:
    metadata:
      labels:
        app: archio-imp-vol
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-import-volume-v9
        name: archio-imp-vol
        ports:
        - containerPort: 3002
          name: archio-imp-vol
