apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cron-count-register-volume
  name: cron-count-register-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-count-register-volume
  template:
    metadata:
      labels:
        app: cron-count-register-volume
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:archio-cron-register-v09
          name: cron-count-register-volume
          envFrom:
            - secretRef:
                name: api-secret
          