
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-export-demand-archive
  name: ms-export-demand-archive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-export-demand-archive
  template:
    metadata:
      labels:
        app: ms-export-demand-archive
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:ms-export-demand-archive-v0001
        
          name: ms-export-demand-archive
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS   
            