apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: ms-general-archives
  name: ms-general-archives
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ms-general-archives
  template:
    metadata:
      labels:
        app: ms-general-archives
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-general-archives-v01
        name: ms-general-archives
        ports:
        - containerPort: 3049
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                
                               