apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: ms-restruct-archives
  name: ms-restruct-archives
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-restruct-archives
  template:
    metadata:
      labels:
        app: ms-restruct-archives
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-archive-reduce-document-v09 para fazer amanhá
      - image: archiocloud/develop:archio-restruct-archives-v03
        name: ms-restruct-archives
        ports:
        - containerPort: 3034
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                
                               