apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: ms-restruct-dct-arc
  name: ms-restruct-dct-arc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-restruct-dct-arc
  template:
    metadata:
      labels:
        app: ms-restruct-dct-arc
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-restruct-document-archives-v2 
      
        name: ms-restruct-dct-arc
        ports:
        - containerPort: 3035
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            - name: REDIS_PORT
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: REDIS_PORT                
