apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: ms-workseet-save
  name: ms-workseet-save
spec:
  replicas: 8
  selector:
    matchLabels:
      app: ms-workseet-save
  template:
    metadata:
      labels:
        app: ms-workseet-save
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-ms-workseet-save-v2
        name: ms-workseet-save
        ports:
        - containerPort: 3043
        env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS 
            