
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-data-volumes
  name: stream-data-volumes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stream-data-volumes
  template:
    metadata:
      labels:
        app: stream-data-volumes
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        # - image: archiocloud/develop:archio-iterator-volumes-v3005
        # testes de exportacao
        - image: archiocloud/develop:archio-iterator-volumes-v4010 
        
          name: stream-data-volumes
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS   
            - name: RABBITMQ_IMPORT_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_IMPORT_CONNECTION_URL         
            