apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-data-archive
  name: stream-data-archive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stream-data-archive
  template:
    metadata:
      labels:
        app: stream-data-archive
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        # - image: archiocloud/develop:archio-iterator-v609 ## estavel
        - image: archiocloud/develop:archio-iterator-v3005
          name: stream-data-archive
          env:
            - name: RABBITMQ_CONNECTION_URL
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: RABBITMQ_CONNECTION_URL
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-archio-all
                  key: MONGO_ACESS      
            