apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-data-archive
  name: stream-data-archive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-data-archive
  template:
    metadata:
      labels:
        app: stream-data-archive
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        # - image: archiocloud/develop:archio-iterator-v609 ## estavel
        - image: archiocloud/develop:archio-iterator-v611
          name: stream-data-archive
          envFrom:
            - secretRef:
                name: api-secret
          # resources:
          #   limits:
          #     memory: 300Mi
          #     cpu: 500m    
          