
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-data-volumes
  name: stream-data-volumes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-data-volumes
  template:
    metadata:
      labels:
        app: stream-data-volumes
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        # - image: archiocloud/develop:archio-iterator-v511
        # - image: archiocloud/develop:archio-iterator-v512 ## tem q converter no qa versao esta inferior 316
        - image: archiocloud/develop:archio-iterator-volumes-v4 ## estavel
          name: stream-data-volumes
          envFrom:
            - secretRef:
                name: api-secret
          # resources:
          #   limits:
          #     memory: 300Mi
          #     cpu: 500m    
          