apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mslretenvol
  name: mslretenvol
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mslretenvol
  template:
    metadata:
      labels:
        app: mslretenvol
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:mslretentionvolume-v203
          name: mslretenvol
          ports:
          - containerPort: 3031
            name: mslretenvol
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  