apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mslcalctemp
  name: mslcalctemp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mslcalctemp
  template:
    metadata:
      labels:
        app: mslcalctemp
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:msl-calculate-temporality-v111 #vida real
        # - image: archiocloud/develop:msl-calculate-temporality-v108 #vida real
          name: mslcalctemp
          ports:
          - containerPort: 3020
            name: mslcalctemp
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  