apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mslvolcalcitens
  name: mslvolcalcitens
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mslvolcalcitens
  template:
    metadata:
      labels:
        app: mslvolcalcitens
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:mslvolumecalculateitens-v203
          name: mslvolcalcitens
          ports:
          - containerPort: 3041
            name: mslvolcalcitens
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  