apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mslvolcaclbisma
  name: mslvolcaclbisma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mslvolcaclbisma
  template:
    metadata:
      labels:
        app: mslvolcaclbisma
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
        - image: archiocloud/develop:mslvolumecalculatebiggerandsmalleryear-v201
          name: mslvolcaclbisma
          ports:
          - containerPort: 3051
            name: mslvolcaclbisma
          env:
            - name: AMPQ_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-ampq-queue
                  key: AMPQ_QUEUE
            - name: CLOUD_QUEUE
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-cloud-queue
                  key: CLOUD_QUEUE      
            - name: KULSTER_QUEUES
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-kluster-queue
                  key: KULSTER_QUEUES            
            - name: MONGO_ACESS
              valueFrom:
                 secretKeyRef: 
                  name: api-sec-mongo-access
                  key: MONGO_ACESS                  