apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec: 
  tls:
  - hosts:
    - "cl.archio.com.br"
    secretName: api-secret-prod
  rules:
    - host: cl.archio.com.br
      http:
        paths:
        - path: /
          backend:
            serviceName: archio-main
            servicePort: 80
    - host: cl.archio.com.br
      http:
        paths:
        - path: /export
          backend:
            serviceName: export-archio
            servicePort: 80  
    - host: cl.archio.com.br
      http:
        paths:
        - path: /queues
          backend:
            serviceName: rabbitmq
            servicePort: 80                      
        