apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cluster.archio.com.br
      http:
        paths:
        - path: /
          backend:
            serviceName: archio-main
            servicePort: 80
    - host: cluster.archio.com.br
      http:
        paths:
        - path: /export
          backend:
            serviceName: export-archio
            servicePort: 80  
    - host: cluster.archio.com.br
      http:
        paths:
        - path: /queues
          backend:
            serviceName: rabbitmq
            servicePort: 80                      
        