apiVersion: v1
kind: Service
metadata:
  labels:
    app: msimportarchive
  name: msimportarchive
spec:
  type: ClusterIP
  ports:
  - name: "msimportarchive"
    port: 1001
    targetPort: 1001   
  selector:
    app: msimportarchive