apiVersion: v1
kind: Service
metadata:
  labels:
    app: msretenvol
  name: msretenvol
spec:
  type: ClusterIP
  ports:
  - name: "msretenvol"
    port: 3030
    targetPort: 3030   
  selector:
    app: msretenvol