apiVersion: v1
kind: Service
metadata:
  labels:
    app: msvolcalcitens
  name: msvolcalcitens
spec:
  type: ClusterIP
  ports:
  - name: "msvolcalcitens"
    port: 3040
    targetPort: 3040 
  selector:
    app: msvolcalcitens