apiVersion: v1
kind: Service
metadata:
  labels:
    app: mslvolcalcitens
  name: mslvolcalcitens
spec:
  type: ClusterIP
  ports:
  - name: "mslvolcalcitens"
    port: 3041
    targetPort: 3041
  selector:
    app: mslvolcalcitens