apiVersion: v1
kind: Service
metadata:
  labels:
    app: mslretenvol
  name: mslretenvol
spec:
  type: ClusterIP
  ports:
  - name: "mslretenvol"
    port: 3031
    targetPort: 3031   
  selector:
    app: mslretenvol