apiVersion: v1
kind: Service
metadata:
  labels:
    app: mslcalctemp
  name: mslcalctemp
spec:
  type: ClusterIP
  ports:
  - name: "mslcalctemp"
    port: 3020
    targetPort: 3020   
  selector:
    app: mslcalctemp