apiVersion: v1
kind: Service
metadata:
  labels:
    app: mslvolcaclbisma
  name: mslvolcaclbisma
spec:
  type: ClusterIP
  ports:
  - name: "mslvolcaclbisma"
    port: 3051
    targetPort: 3051
  selector:
    app: mslvolcaclbisma