apiVersion: v1
kind: Secret
metadata:
  name: api-sec-mongo-access
type: Opaque
data:
  MONGO_ACESS: bW9uZ29kYjovL2RldmVsb3BhcmNoaW86NzFnR3lhNzR6V0hMRU44NUBjbHVzdGVyMC1zaGFyZC0wMC0wMC1ycjZzeC5tb25nb2RiLm5ldDoyNzAxNy9lYXJjaGl2ZT9zc2w9dHJ1ZSZyZXBsaWNhU2V0PUNsdXN0ZXIwLXNoYXJkLTAmYXV0aFNvdXJjZT1hZG1pbg==
  

