apiVersion: v1
kind: Secret
metadata:
  name: api-sec-ampq-queue
type: Opaque
data:
  AMPQ_QUEUE: YW1xcHM6Ly94ZGNqaGplbTpLXzcxY2dNZ0VHWmgtWXIweXFXUWc4c1VBSUZSQWVvaEBrZWJuZWthaXNlLmxtcS5jbG91ZGFtcXAuY29tL3hkY2poamVt


  
  

