apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bW9uZ291c2Vy  # Base64 encoded 'mongouser'
  mongo-root-password: cGFzc3dvcmQxMjM=  # Base64 encoded 'password123'
