apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-main
  template:
    metadata:
      labels:
        app: archio-main
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      # - image: archiocloud/develop:archio-main-v72 
      # - image: archiocloud/develop:archio-main-v79
      - image: archiocloud/develop:archio-main-v105
     
        name: archio-main        
        ports:
        - containerPort: 3000
          name: archio-main    
        envFrom:
            - secretRef:
                name: api-secret
          
            
