# apiVersion: v1
# kind: Service
# metadata:
#   name: plans-lb-svc
# spec:
#   selector:
#     app: admin-plans
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer


apiVersion: v1
kind: Service
metadata:
  name: admin-plans-internal-svc
spec:
  selector:
    app: admin-plans
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
