# apiVersion: v1
# kind: Service
# metadata:
#   name: admin-user-lb-svc
# spec:
#   selector:
#     app: admin-user
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer

# #     app: gateway
apiVersion: v1
kind: Service
metadata:
  name: admin-user-internal-svc
spec:
  selector:
    app: admin-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
