# apiVersion: v1
# kind: Service
# metadata:
#   name: sponsor-lb-svc
# spec:
#   selector:
#     app: admin-sponsor
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: admin-sponsor-internal-svc
spec:
  selector:
    app: admin-sponsor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 

