# apiVersion: v1
# kind: Service
# metadata:
#   name: profiles-lb-svc
# spec:
#   selector:
#     app: profiles
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: profiles-internal-svc
spec:
  selector:
    app: profiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
