# apiVersion: v1
# kind: Service
# metadata:
#   name: users-lb-svc
# spec:
#   selector:
#     app: users
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer
  

apiVersion: v1
kind: Service
metadata:
  name: users-internal-svc
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
