apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-mupload
  name: archio-mupload 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: archio-mupload
  template:
    metadata:
      labels:
        app: archio-mupload
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-multupload-v9
        name: archio-mupload        
        ports:
        - containerPort: 2000
          name: archio-mupload
