apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-imp-arc
  name: archio-imp-arc
spec:
  type: ClusterIP
  ports:
  - name: "archio-imp-arc"
    port: 3005
    targetPort: 3005   
  selector:
    app: archio-imp-arc