apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-main
  name: archio-main  
spec:
  type: ClusterIP
  ports:
  - name: "archio-main-service"
    port: 80
    targetPort: 3000    
  selector:
    app: archio-main