apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-red-document
  name: archio-red-document
spec:
  type: ClusterIP
  ports:
  - name: "archio-red-document"
    port: 3033
    targetPort: 3033   
  selector:
    app: archio-red-document