apiVersion: v1
kind: Service
metadata:
  labels:
    app: archio-red-departament
  name: archio-red-departament
spec:
  type: ClusterIP
  ports:
  - name: "archio-red-departament"
    port: 3032
    targetPort: 3032   
  selector:
    app: archio-red-departament