apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: archio-supload
  name: archio-supload 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archio-supload
  template:
    metadata:
      labels:
        app: archio-supload
    spec:
      imagePullSecrets:
        - name: pullsecret
      containers:
      - image: archiocloud/develop:archio-sultupload-v1
        name: archio-supload        
        ports:
        - containerPort: 2002
          name: archio-supload
